In [1]:
import numpy as np

In [2]:
df = pd.read_csv('traj.csv', index_col=None, header=0)
df.head()

,"""label"",","""point_count"",","""start_time"",","""end_time"",","""speed_min"",","""speed_max"",","""speed_mean"",","""speed_median"",","""speed_std"",","""acceleration_min"",",...,"""bearing_rate_min"",","""bearing_rate_max"",","""bearing_rate_mean"",","""bearing_rate_median"",","""bearing_rate_std"",","""bearing_rate_rate_min"",","""bearing_rate_rate_max"",","""bearing_rate_rate_mean"",","""bearing_rate_rate_median"",","""bearing_rate_rate_std"""
0,train,69,1206687174,1206691199,0.0,31.935446,15.454553,14.301758,12.707371,-0.196530,...,-77.929197,5.968814,-2.151842,0.000000,12.893332,-77.929197,5.968814,-2.151842,0.000000,12.893332
1,train,379,1206691200,1206712920,0.0,32.975181,18.186951,18.628584,12.455608,-0.191297,...,-89.728954,86.893676,-1.092658,0.000000,12.081042,-89.728954,86.893676,-1.092658,0.000000,12.081042
2,train,801,1206725270,1206777599,0.0,32.640630,20.757469,23.583678,10.391102,-0.227566,...,-89.340771,67.957485,0.272561,0.000000,7.791245,-89.340771,67.957485,0.272561,0.000000,7.791245
3,train,716,1206777600,1206863999,0.0,66.636192,18.627297,21.060842,10.349662,-0.724322,...,-75.475064,33.282345,-0.029642,0.000000,3.595624,-75.475064,33.282345,-0.029642,0.000000,3.595624
4,train,316,1206864000,1206904391,0.0,36.472382,18.993953,23.836840,10.195738,-2.605169,...,-82.031770,24.074061,-0.609431,-0.003406,6.890668,-82.031770,24.074061,-0.609431,-0.003406,6.890668

In [3]:
df.columns = df.columns.str.replace("\"", "")
df.columns = df.columns.str.replace(",", "")
df.columns = df.columns.str.replace(",", "")
df.columns = df.columns.str.strip()
df.head()

,label,point_count,start_time,end_time,speed_min,speed_max,speed_mean,speed_median,speed_std,acceleration_min,...,bearing_rate_min,bearing_rate_max,bearing_rate_mean,bearing_rate_median,bearing_rate_std,bearing_rate_rate_min,bearing_rate_rate_max,bearing_rate_rate_mean,bearing_rate_rate_median,bearing_rate_rate_std
0,train,69,1206687174,1206691199,0.0,31.935446,15.454553,14.301758,12.707371,-0.196530,...,-77.929197,5.968814,-2.151842,0.000000,12.893332,-77.929197,5.968814,-2.151842,0.000000,12.893332
1,train,379,1206691200,1206712920,0.0,32.975181,18.186951,18.628584,12.455608,-0.191297,...,-89.728954,86.893676,-1.092658,0.000000,12.081042,-89.728954,86.893676,-1.092658,0.000000,12.081042
2,train,801,1206725270,1206777599,0.0,32.640630,20.757469,23.583678,10.391102,-0.227566,...,-89.340771,67.957485,0.272561,0.000000,7.791245,-89.340771,67.957485,0.272561,0.000000,7.791245
3,train,716,1206777600,1206863999,0.0,66.636192,18.627297,21.060842,10.349662,-0.724322,...,-75.475064,33.282345,-0.029642,0.000000,3.595624,-75.475064,33.282345,-0.029642,0.000000,3.595624
4,train,316,1206864000,1206904391,0.0,36.472382,18.993953,23.836840,10.195738,-2.605169,...,-82.031770,24.074061,-0.609431,-0.003406,6.890668,-82.031770,24.074061,-0.609431,-0.003406,6.890668

In [4]:
classes = {
            "walk":0,
            "bike":1,
            "bus":2,
            "taxi": 3,
            "car":3, 
            "subway":4, 
            "train":4, 
            "airplane":6, 
            "boat":7, 
            "run":8, 
            "motorcycle":10
        }

In [5]:
df = df.replace({'label':classes})
df['label'].unique()

array([ 4,  3,  0,  2,  6,  1,  7,  8, 10], dtype=int64)

In [6]:
df['label']=df['label'].astype(int)

In [7]:
selected_classes = df[df['label']<5]
selected_classes['label'].unique()

array([4, 3, 0, 2, 1], dtype=int64)

In [8]:
inv_map = {v: k for k, v in classes.items()}

In [9]:
inv_map

{0: 'walk',
 1: 'bike',
 2: 'bus',
 3: 'car',
 4: 'train',
 6: 'airplane',
 7: 'boat',
 8: 'run',
 10: 'motorcycle'}

In [10]:
selected_classes = selected_classes.replace({'label':inv_map})
selected_classes['label'].unique()

array(['train', 'car', 'walk', 'bus', 'bike'], dtype=object)

In [11]:
mode_mean=selected_classes.groupby(['label'])['speed_mean'].mean().to_frame(name = 'mode_mean').reset_index()
mode_mean.head()

   label  mode_mean
0   bike   3.248344
1    bus   5.567865
2    car   8.799230
3  train  12.787024
4   walk   1.832925

In [12]:
data_mean= selected_classes.merge(mode_mean, left_on='label', right_on='label')
data_mean.head()

,label,point_count,start_time,end_time,speed_min,speed_max,speed_mean,speed_median,speed_std,acceleration_min,...,bearing_rate_max,bearing_rate_mean,bearing_rate_median,bearing_rate_std,bearing_rate_rate_min,bearing_rate_rate_max,bearing_rate_rate_mean,bearing_rate_rate_median,bearing_rate_rate_std,mode_mean
0,train,69,1206687174,1206691199,0.0,31.935446,15.454553,14.301758,12.707371,-0.196530,...,5.968814,-2.151842,0.000000,12.893332,-77.929197,5.968814,-2.151842,0.000000,12.893332,12.787024
1,train,379,1206691200,1206712920,0.0,32.975181,18.186951,18.628584,12.455608,-0.191297,...,86.893676,-1.092658,0.000000,12.081042,-89.728954,86.893676,-1.092658,0.000000,12.081042,12.787024
2,train,801,1206725270,1206777599,0.0,32.640630,20.757469,23.583678,10.391102,-0.227566,...,67.957485,0.272561,0.000000,7.791245,-89.340771,67.957485,0.272561,0.000000,7.791245,12.787024
3,train,716,1206777600,1206863999,0.0,66.636192,18.627297,21.060842,10.349662,-0.724322,...,33.282345,-0.029642,0.000000,3.595624,-75.475064,33.282345,-0.029642,0.000000,3.595624,12.787024
4,train,316,1206864000,1206904391,0.0,36.472382,18.993953,23.836840,10.195738,-2.605169,...,24.074061,-0.609431,-0.003406,6.890668,-82.031770,24.074061,-0.609431,-0.003406,6.890668,12.787024

In [13]:
mode_std=selected_classes.groupby(['label'])['speed_mean'].std().to_frame(name = 'mode_std').reset_index()
mode_std.head()

   label  mode_std
0   bike  1.211392
1    bus  2.641462
2    car  3.876316
3  train  9.547416
4   walk  2.136522

In [14]:
stdev= data_mean.merge(mode_std, left_on='label', right_on='label')
stdev.head()

,label,point_count,start_time,end_time,speed_min,speed_max,speed_mean,speed_median,speed_std,acceleration_min,...,bearing_rate_mean,bearing_rate_median,bearing_rate_std,bearing_rate_rate_min,bearing_rate_rate_max,bearing_rate_rate_mean,bearing_rate_rate_median,bearing_rate_rate_std,mode_mean,mode_std
0,train,69,1206687174,1206691199,0.0,31.935446,15.454553,14.301758,12.707371,-0.196530,...,-2.151842,0.000000,12.893332,-77.929197,5.968814,-2.151842,0.000000,12.893332,12.787024,9.547416
1,train,379,1206691200,1206712920,0.0,32.975181,18.186951,18.628584,12.455608,-0.191297,...,-1.092658,0.000000,12.081042,-89.728954,86.893676,-1.092658,0.000000,12.081042,12.787024,9.547416
2,train,801,1206725270,1206777599,0.0,32.640630,20.757469,23.583678,10.391102,-0.227566,...,0.272561,0.000000,7.791245,-89.340771,67.957485,0.272561,0.000000,7.791245,12.787024,9.547416
3,train,716,1206777600,1206863999,0.0,66.636192,18.627297,21.060842,10.349662,-0.724322,...,-0.029642,0.000000,3.595624,-75.475064,33.282345,-0.029642,0.000000,3.595624,12.787024,9.547416
4,train,316,1206864000,1206904391,0.0,36.472382,18.993953,23.836840,10.195738,-2.605169,...,-0.609431,-0.003406,6.890668,-82.031770,24.074061,-0.609431,-0.003406,6.890668,12.787024,9.547416

In [15]:
def std_dev(speed_mean,mode_mean,mode_std): 
    if (speed_mean < mode_mean - 2 * mode_std):
        return 1
    elif (speed_mean > mode_mean + 2 * mode_std):
        return 1
    else:
        return 0

In [16]:
stdev["to_remove"] = stdev.apply(lambda x: std_dev(x["speed_mean"],x["mode_mean"],x["mode_std"]), axis=1)
stdev.head()

,label,point_count,start_time,end_time,speed_min,speed_max,speed_mean,speed_median,speed_std,acceleration_min,...,bearing_rate_median,bearing_rate_std,bearing_rate_rate_min,bearing_rate_rate_max,bearing_rate_rate_mean,bearing_rate_rate_median,bearing_rate_rate_std,mode_mean,mode_std,to_remove
0,train,69,1206687174,1206691199,0.0,31.935446,15.454553,14.301758,12.707371,-0.196530,...,0.000000,12.893332,-77.929197,5.968814,-2.151842,0.000000,12.893332,12.787024,9.547416,0
1,train,379,1206691200,1206712920,0.0,32.975181,18.186951,18.628584,12.455608,-0.191297,...,0.000000,12.081042,-89.728954,86.893676,-1.092658,0.000000,12.081042,12.787024,9.547416,0
2,train,801,1206725270,1206777599,0.0,32.640630,20.757469,23.583678,10.391102,-0.227566,...,0.000000,7.791245,-89.340771,67.957485,0.272561,0.000000,7.791245,12.787024,9.547416,0
3,train,716,1206777600,1206863999,0.0,66.636192,18.627297,21.060842,10.349662,-0.724322,...,0.000000,3.595624,-75.475064,33.282345,-0.029642,0.000000,3.595624,12.787024,9.547416,0
4,train,316,1206864000,1206904391,0.0,36.472382,18.993953,23.836840,10.195738,-2.605169,...,-0.003406,6.890668,-82.031770,24.074061,-0.609431,-0.003406,6.890668,12.787024,9.547416,0

In [19]:
len(stdev)

9589

In [18]:
noise_removed = stdev[stdev['to_remove']!=1]
len(noise_removed)

9325

In [17]:
noise_removed.to_excel('noise_removed.xls')